// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Andyyy.Models;

public partial class WorkSheet
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime CreateDateTime { get; set; }

    public DateTime UpDateTime { get; set; }
}